### PR TITLE
Add `CHANGELOG` entry for `Automaton`-based simulation interface

### PR DESCRIPTION
**Pull request by gergoerdi**
This is to take care of the outstanding issue of https://github.com/clash-lang/clash-compiler/pull/1261

### CODE REVIEW

**Comment by gergoerdi** [comment]
TBH I didn't realize https://github.com/clash-lang/clash-compiler/pull/1261 hasn't been merged yet, and I have been using it in my book :)

**Comment by christiaanb** [comment]
Yeah, I was basically waiting for you to tell us whether it was the API that worked well. That is, #1261 implements the API initially suggested, but perhaps it wasn't the one ultimately required.

**Comment by gergoerdi** [comment]
> Yeah, I was basically waiting for you to tell us whether it was the API that worked well. That is, #1261 implements the API initially suggested, but perhaps it wasn't the one ultimately required.

Well in that case, let me quickly test it out by modifying `retroclash-sim` to use it, and I'll get back to you pronto.

**Comment by gergoerdi** [comment]
> > Yeah, I was basically waiting for you to tell us whether it was the API that worked well. That is, #1261 implements the API initially suggested, but perhaps it wasn't the one ultimately required.
> 
> Well in that case, let me quickly test it out by modifying `retroclash-sim` to use it, and I'll get back to you pronto.

Hmm, tried this merged into e6ee4fb929af4fbe2b8a0695b1f33aa07bf91ef2 with both the Brainfuck machine and the Tiny BASIC computer, and both seem to have a space leak. However, the leak is there even when using the non-Automaton-based simulation interface, so it seems like an unrelated problem (perhaps a regression on https://github.com/clash-lang/clash-compiler/issues/1256 ?). I will need to do a more thorough checking.

**Comment by gergoerdi** [comment]
> > > Yeah, I was basically waiting for you to tell us whether it was the API that worked well. That is, #1261 implements the API initially suggested, but perhaps it wasn't the one ultimately required.
> > 
> > 
> > Well in that case, let me quickly test it out by modifying `retroclash-sim` to use it, and I'll get back to you pronto.
> 
> Hmm, tried this merged into [e6ee4fb](https://github.com/clash-lang/clash-compiler/commit/e6ee4fb929af4fbe2b8a0695b1f33aa07bf91ef2) with both the Brainfuck machine and the Tiny BASIC computer, and both seem to have a space leak. However, the leak is there even when using the non-Automaton-based simulation interface, so it seems like an unrelated problem (perhaps a regression on #1256 ?). I will need to do a more thorough checking.

OK please disregard this whole thread -- it seems the space leak is caused by using a `ClearOnReset` block RAM. I will isolate and report that separately, but it has absolutely nothing to do with the `Automaton`-based simulation interface.

**Please proceed in merging #1261**.

**Comment by christiaanb** [comment]
It seems there's a new release of `primitive` that introduced `NFData ByteArray`, and so the CI failure has of course nothing to do with this change. I'll fix the NFData issue separately.

**Pull request merged**
