### PR TITLE
Make 'mapSignal#' lazy in its Signal argument

### LINKED ISSUE #1521: `mapSignal#` is too strict in its `Signal` argument
Consider this beautiful piece of code:

```haskell
let
  f (_, b) = (b, b)
  s = f <$> liftA2 (,) (fst <$> s) (pure 'a')
  ((a,_):_) = sample @(Signal System) s
in
  evaluate a >> pure ()
```

Evaluation currently approximates:

1. evaluate `a`
2. evaluate `s`
3. evaluate `liftA2 (,) (fst <$> s) (pure 'a')`
4. evaluate `fst <$> s`
5. goto (2)

I.e., it gets stuck in an infinite loop. If `mapSignal#` (hidden in the `liftA2` call) were lazy in its signal argument, `evaluate a` would terminate. Patch:

```diff
diff --git a/clash-prelude/src/Clash/Signal/Internal.hs b/clash-prelude/src/Clash/Signal/Internal.hs
index cf9763d9..f7a67ea9 100644
--- a/clash-prelude/src/Clash/Signal/Internal.hs
+++ b/clash-prelude/src/Clash/Signal/Internal.hs
@@ -660,7 +660,7 @@ mapSignal# f = go
  where
   -- See -fstrict-mapSignal documentation in clash-prelude.cabal
   theSeq = if fStrictMapSignal then seqX else flip const
-  go (a :- as) = f a :- (a `theSeq` go as)
+  go ~(xs@(a :- as)) = f a :- (a `theSeq` (xs `seq` go as))
 {-# NOINLINE mapSignal# #-}
 {-# ANN mapSignal# hasBlackBox #-}
```

### PR DESCRIPTION
**Pull request by martijnbastiaan**
Closes #1521

### CODE REVIEW

**Comment by alex-mckenna** [comment]
Is there any chance of this making things worse on client code? I don't want to play wack-a-mole with `mapSignal#` bugs :hammer: 
If you're reasonably confident the answer to that is "no" then I'll accept if CI is happy

**Comment by alex-mckenna** [comment]
Oh also, can you add a changelog please

**Comment by martijnbastiaan** [comment]
> Oh also, can you add a changelog please

Sure, thanks for noticing!

> Is there any chance of this making things worse on client code? 

Yes and no. 

* No: `mapSignal#` is a primitive. HDL should therefore be unaffected.
* Yes: this might induce a slight performance penalty when simulating. However.. I'm having a suspicion that a lot of one of our client's laziness issues have been caused by this. (Which they have mitigated by sprinkling lazy pattern matches around in their own code..)

**Comment by alex-mckenna** [comment]
Hmm, do we have a benchmark somewhere that could give us an idea whether simulation is affected?

**Comment by martijnbastiaan** [comment]
Yah, it wouldn't hurt to set something up. Having said that; the current behavior is just wrong (at the very least unexpected!), so the results would have to be really shocking in order to justify not merging this IMO. What do you think?

**Comment by alex-mckenna** [comment]
Agreed: if there's no benchmark at hand then I think this can be merged if we make an issue to benchmark something encompassing this issue (e.g. benchmark signal primitives). At least then we can hopefully show performance is reasonable and there are no massive space leaks popping up (plus having benchmarks could help us spot issues like this in the future).

**Comment by martijnbastiaan** [comment]
The benchmark:

```diff
diff --git a/tests/shouldwork/Basic/AES.hs b/tests/shouldwork/Basic/AES.hs
index aa849b83..d201a548 100644
--- a/tests/shouldwork/Basic/AES.hs
+++ b/tests/shouldwork/Basic/AES.hs
@@ -1,5 +1,7 @@
 module AES where
 
+import qualified Prelude as P
+
 import Clash.Prelude
 import Data.Bool
 
@@ -109,3 +111,19 @@ aes start key block = bundle (cnt, roundKey, pack <$> roundState, cnt .==. 11)
 
 topEntity clk rst en =
   withClockResetEnable @System clk rst en (aes @System)
+
+main :: IO ()
+main = do
+  let
+    circuit =
+      topEntity
+        clockGen
+        resetGen
+        enableGen
+        (fromList (P.concat (P.repeat (True:P.replicate 30 False))))
+        (fromList (P.iterate succ minBound))
+        (fromList (P.iterate pred maxBound))
+
+    (_, roundKey, _, _) = sample circuit P.!! 10000
+
+  putStrLn (show roundKey)
```

Run with this patch:

```
martijn@deskei:~/code/zcompiler$ hyperfine --warmup 3 ./main_with_patch 
Benchmark #1: ./main_with_patch
  Time (mean ± σ):      1.333 s ±  0.009 s    [User: 1.330 s, System: 0.003 s]
  Range (min … max):    1.323 s …  1.354 s    10 runs
```

run without:

```
martijn@deskei:~/code/zcompiler$ hyperfine --warmup 3 ./main
Benchmark #1: ./main
  Time (mean ± σ):      1.332 s ±  0.008 s    [User: 1.324 s, System: 0.008 s]
  Range (min … max):    1.324 s …  1.352 s    10 runs
```

**Review by alex-mckenna — APPROVED** [review]

**Pull request merged**
