### PR TITLE
clash-lib: Print constructor names in netlist errors

### PR DESCRIPTION
**Pull request by bgamari**
While debugging a netlist generation failure I found this output to be useful.

### CODE REVIEW

**Review by martijnbastiaan — APPROVED** [review]
Makes a lot of sense to me. Could you rebase? I think something went wrong in the release process, so you might need to cherry-pick:

```
git fetch
git reset origin/master --hard
git cherry-pick b9177138e3e6a8a9e507ae031210c6cef5f6e9ac
git push -f
```

**Comment by bgamari** [comment]
Rebased.

**Comment by martijnbastiaan** [comment]
CI doesn't pass because of warnings - you probably want to mention `nm` in the various error messages. Could you fix them?

**Comment by bgamari** [comment]
Oh dear, indeed what a mess. I rather don't need to bind `nm` at all as I belive `dcNm` is sufficient for our purposes.

**Comment by martijnbastiaan** [comment]
@kloonbot run_ci db3f9d9bed0bf5eec5a6cf1e24c8a6664eadb7f7

**Pull request merged**
