### PR TITLE
Created stack template.

### LINKED ISSUE #1582: Support Stack templates
It would be nice if, instead of making users download / unpack the Clash starter project, to add a [Stack template repository](https://docs.haskellstack.org/en/stable/GUIDE/#templates). Setting up a new Clash project would be as easy as running:

```
stack new my-clash-project clash-lang/simple
```

This would eliminate the need for users to go through all the files in the starter project and replace them with appropriate values. We should also start promoting this on clash-lang.org.

### PR DESCRIPTION
**Pull request by rowanG077**
Fixes #1582

I have left the license exactly as the starter project but maybe it's better to remove it completely.

### CODE REVIEW

**Comment by alex-mckenna** [comment]
IMO the license for this shouldn't be the same as the starter project (CC0). This isn't a project of ours left out as an example, the main use would be people creating their own projects which likely want less permissive licences. I would lean towards using some variant of the BSD license as this is _probably_ the most common for Haskell projects anyway.

**Comment by martijnbastiaan** [comment]
Ooh this is great, thanks @rowanG077! 

There's a number of organizational issues we need to address I think:

* It would be neat if we could use a simpler `stack new my-clash-project clash-lang/simple` instead. This would require us to make a separate repository `stack-templates`.

* We currently risk the starter project and the stack template going out of sync. Ideally, we would generate one from the other.

I think this should look like:

 * A repository `clash-lang/stack-templates`, which has a readme redirecting to `clash-lang/clash-starters`.
 * A push to stack templates would trigger a CI that builds all the templates and pushes them to `clash-lang/clash-starters` with some default config
 * `clash-lang/clash-starters` contain a number of subdirectories. One for each rendered Stack template. It would instuct Stack users to use `stack new foo/bar`, while instructing cabal users to use `curl foo.tar.gz | untar bar`.

I'm pushing for multiple templates, because it would be cool if we could point users to user `stack new clash-lang/aws` for a starter project containing all the setup foo for running Clash on AWS (for example)!

@alex-mckenna @rowanG077 what do you think?

**Comment by alex-mckenna** [comment]
It sounds like `clash-lang/clash-starters` would just be a repository of build artefacts. Why not have something more like releases for `clash-lang/stack-templates` with ready to extract and use archives? If it is a single repo with releases, you would also probably want the `clash-lang/clash-starters` name instead of `stack-templates` for discoverability.

Multiple templates is a :+1:  from me, the needs of someone deploying to something different like F1 are suitably different, as is the _hello world_ example to include by default in the project.

**Comment by martijnbastiaan** [comment]
> name instead of `stack-templates` for discoverability.

To motivate that name a bit: it's the default repository Stack looks for when downloading templates, so it keeps the `new` command nice and short.

**Comment by alex-mckenna** [comment]
Makes sense, slightly annoying but I guess that comes with using `stack`. Would it be possible to edit the most recent release of `clash-lang/clash-compiler` to include the new starter project builds? I know you can edit releases but there may be limitations which stop this

**Comment by martijnbastiaan** [comment]
I don't believe there are any limitations. We'd just have to figure out how to use the GitHub API.

**Comment by alex-mckenna** [comment]
Hopefully that's not too much of a limitation for _Meneer DevOps_

**Comment by martijnbastiaan** [comment]
:unamused:

**Comment by rowanG077** [comment]
If you make the repos I can try to get this working. I have done something like this before :). @martijnbastiaan

**Comment by martijnbastiaan** [comment]
Yay! I've given you write access to:

* https://github.com/clash-lang/clash-starters
* https://github.com/clash-lang/stack-templates

**Comment by martijnbastiaan** [comment]
Closing in favor of https://github.com/clash-lang/stack-templates/pull/2. Thanks :)

**Pull request closed without merging**
