### PR TITLE
Add `instance Ix` for `Unsigned` and `Signed`.

### PR DESCRIPTION
**Pull request by gergoerdi**
This allows using `Signed n` and `Unsigned n` as `Data.Array` indices,
for example in test benches that simulate memory.

### CODE REVIEW

**Comment by alex-mckenna** [comment]
Not to nitpick, but as you're not defining any of the GHC-specific unsafe `Ix` functions, would you also mind changing from `GHC.Arr` to `Data.Ix`?

**Comment by gergoerdi** [comment]
> Not to nitpick, but as you're not defining any of the GHC-specific unsafe `Ix` functions, would you also mind changing from `GHC.Arr` to `Data.Ix`?

That's fair, I'll do that. But hopefully we'll get `indexError` back... https://gitlab.haskell.org/ghc/ghc/-/issues/18579

**Comment by gergoerdi** [comment]
> Not to nitpick, but as you're not defining any of the GHC-specific unsafe `Ix` functions, would you also mind changing from `GHC.Arr` to `Data.Ix`?

I've done this just now.

**Comment by martijnbastiaan** [comment]
Cool! I think we can merge it after a CHANGELOG entry.

**Comment by gergoerdi** [comment]
> Cool! I think we can merge it after a CHANGELOG entry.

But the git log shows that `CHANGELOG` is updated after-the-fact, at release time, not in individual commits.

**Comment by martijnbastiaan** [comment]
That's true, but we keep each entry as a file so we can easily backport / update the changelog later. See:

* https://github.com/clash-lang/clash-compiler/blob/master/changelog/README.md
* https://github.com/clash-lang/clash-compiler/tree/master/changelog

**Comment by gergoerdi** [comment]
> That's true, but we keep each entry as a file so we can easily backport / update the changelog later.

The friction is real...

**Comment by martijnbastiaan** [comment]
> The friction is real...

ikr..

**Pull request merged**
