### PR TITLE
Enable documentation checks on all but two pkgs

### PR DESCRIPTION
**Pull request by martijnbastiaan**
Currently not checking `clash-lib` as it still fails these checks.
`clash-lib-hedgehog` is blocked on issue https://github.com/clash-lang/clash-compiler/issues/2462.

## Still TODO:

  - [X] ~~Write a changelog entry (see changelog/README.md)~~
  - [X] ~~Check copyright notices are up to date in edited files~~

### CODE REVIEW

**Comment by DigitalBrains1** [comment]
I thought it would be trivial to extend this to anything but `clash-lib`... but I've learned that there are more ways in which these Haddock warnings can crop up than I had initially realised. Still, I extended it, it just wasn't as trivial. Here's my extended version:

https://github.com/clash-lang/clash-compiler/tree/peter/clash-cores-docs

Can I interest you in picking that one instead? You can just force-push that HEAD on here.

**Comment by DigitalBrains1** [comment]
I don't know what these things refer to, so I don't know if they could be hyperlinked in the documentation or not:
 * `classifyKind` in `clash-lib-hedgehog:Clash.Hedgehog.Core.Type`
 * `genKind` and `genTypeFrom` in `clash-lib-hedgehog:Clash.Hedgehog.Core.TyCon`

I get the sense maybe the code was refactored and these refer to the old names of functions that have been renamed.

**Comment by alex-mckenna** [comment]
Some pointers which may help:

  - `classifyKind` was replaced with a more general `classify` which is not exported
  - `genKind` was replaced with `genKindFrom` and `genClosedKindFrom` which are exported
  - `genTypeFrom` was replaced with many functions:
    - `genPolyTypeFrom`
    - `genClosedPolyType`
    - `genMonoTypeFrom`
    - `genClosedMonoType`
    - arguably also `genWithCodomain`, depending what you're doing

All of these functions currently live in `Clash.Hedgehog.Core.Type`

**Comment by martijnbastiaan** [comment]
Can't approve my own PR, but :heavy_check_mark: @DigitalBrains1.

**Comment by DigitalBrains1** [comment]
I've edited your cover letter to include the new commit message.

Also, given that two people agree on this PR, I'll merge it.

**Pull request merged**
