### PR TITLE
Add test for (Num) constant folding

### PR DESCRIPTION
**Pull request by leonschoorl**
And fix various issues encountered along the way.

----
Evaluation doesn't work for:
* ~~`countLeadingZeros` and `countTrailingZeros` on any Sized Clash type
  These are implemented in terms of maps and folds which don't evaluate (well).
  An option could be to make them primitives, just like they are for general Haskell numbers.~~
  edit @martijnbastiaan : This has been implemented in https://github.com/clash-lang/clash-compiler/pull/501/commits/44f4dc7b6b88ed9814ab18bb179836aeb06d2298

* `popCount @Integer`
  And there is no blackbox either.
  There isn't really a sensible implementation possible.
  In Haskell `popCount (-3::Integer)` is  `-2`, while popCount is documentated as: "Return the number of set bits in the argument"

* Bits Natural

### CODE REVIEW

**Comment by martijnbastiaan** [comment]
@leonschoorl Could you take a look at https://github.com/clash-lang/clash-compiler/pull/501/commits/44f4dc7b6b88ed9814ab18bb179836aeb06d2298 ? If it makes sense to you, I think we can merge this PR.

**Comment by martijnbastiaan** [comment]
@christiaanb Could you also take a look at https://github.com/clash-lang/clash-compiler/commit/44f4dc7b6b88ed9814ab18bb179836aeb06d2298? We're not sure if this is the correct approach. 

We want:

* The evaluator to pick up on `count{Leading,Trailing}Zeros#` so we can constant fold it

We don't want:

* To implement a blackbox for it

We did this

* by marking the functions as primitive with `primType"  : "Function"`

We're not sure what (unforeseen) consequences our solution has, even though the testsuite passes.

**Comment by martijnbastiaan** [comment]
Well that was the question I suppose. But I see that Clash "silently" adds `NO_TRANSLATION_FOR` to the HDL when `primtype: Function` is there. So to rephrase the question: is there anyway we can add evaluator rules for non-primitives builtin to Clash? We know how to constant fold `countLeadingZeros`, but we're also fine with Clash translating it if it's not used on constants.

**Comment by christiaanb** [comment]
Implement:

```
force# :: a -> a
force# x = x
```

with primitive template `~ARG[0]`

and an evaluator rule that is simply the identity as well.

then add it to the existing implement of CLZ and CTZ. Now, because the `foldr` and `foldl` are an argument to a primitive, so the evaluator will force them to WHNF.

**Comment by martijnbastiaan** [comment]
Clever! We should probably take https://github.com/clash-lang/clash-compiler/issues/499 into account.

**Comment by christiaanb** [comment]
Actually... I'm surprised this doesn't happen already, I mean... basically everything in https://github.com/clash-lang/clash-compiler/blob/580b058618ae4b51f32deb0b69b99ee0698fc430/clash-prelude/src/Clash/Sized/Internal/BitVector.hs#L612-L616 is a primitive. So adding a `force#` shouldn't help.

**Comment by martijnbastiaan** [comment]
`inlineSmall` replaces the call with it's definition if I remember correctly, way before the evaluator gets a chance to look at it.

**Comment by christiaanb** [comment]
Can we take out https://github.com/clash-lang/clash-compiler/pull/501/commits/44f4dc7b6b88ed9814ab18bb179836aeb06d2298 of this PR and then merge it. Leaving https://github.com/clash-lang/clash-compiler/pull/501/commits/44f4dc7b6b88ed9814ab18bb179836aeb06d2298 for a seperate PR.

**Comment by martijnbastiaan** [comment]
yes we can!

**Pull request merged**
