### PR TITLE
Fix various issues in the starter project

### PR DESCRIPTION
**Pull request by martijnbastiaan**

### CODE REVIEW

**Review by alex-mckenna — APPROVED** [review]
Tentative approval: does this mean we're intending to drop snap for good?

**Comment by martijnbastiaan** [comment]
I think it's fine for a classroom environment for now. In case you don't need:

- dependencies from Hackage
- fast executables
- the starter project
- strict versioning

I.e., you just want to synthesize a single file / run clashi. But we should stop promoting it for real:tm: projects.

**Comment by alex-mckenna** [comment]
I wonder how well tools like `cabal-rpm` / `cabal-debian` / `cabal-macosx` work in practice. Perhaps these and a light bit of CI scripting could work?

**Comment by martijnbastiaan** [comment]
Yeah `cabal-debian` works fine. There's a Python script in `bindist/`, but it's a big hackjob. There's lots of annoying details to get right (non-hackage deps, failing doc builds, ..).

**Pull request merged**
