### PR TITLE
Allow BangPatterns on signal

### PR DESCRIPTION
**Pull request by leonschoorl**

### CODE REVIEW

**Comment by leonschoorl** [comment]
I just tried a benchmark with
```haskell
topEntity :: Unsigned 11 -> Unsigned 11
topEntity x = f x

f :: Unsigned 11 -> Unsigned 11
f x = trace (show x) x
{-# NOINLINE f #-}
```

With original $cshow check
```benchmarking normalization of benchmark/tests/TestTraceMono.hs
time                 408.7 μs   (406.4 μs .. 410.9 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 409.4 μs   (407.6 μs .. 413.6 μs)
std dev              8.949 μs   (4.371 μs .. 15.15 μs)
variance introduced by outliers: 14% (moderately inflated)

benchmarking normalization of benchmark/tests/TestTraceMono.hs
time                 405.2 μs   (404.2 μs .. 406.1 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 406.6 μs   (405.1 μs .. 409.7 μs)
std dev              7.194 μs   (3.982 μs .. 11.88 μs)

benchmarking normalization of benchmark/tests/TestTraceMono.hs
time                 407.8 μs   (405.9 μs .. 410.2 μs)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 411.9 μs   (409.1 μs .. 417.0 μs)
std dev              12.15 μs   (8.057 μs .. 19.28 μs)
variance introduced by outliers: 22% (moderately inflated)
```

With $cshow check removed
```
benchmarking normalization of benchmark/tests/TestTraceMono.hs
time                 401.4 μs   (399.6 μs .. 403.1 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 404.1 μs   (402.1 μs .. 408.0 μs)
std dev              8.901 μs   (5.780 μs .. 13.03 μs)
variance introduced by outliers: 14% (moderately inflated)

benchmarking normalization of benchmark/tests/TestTraceMono.hs
time                 401.4 μs   (400.2 μs .. 402.4 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 401.6 μs   (400.2 μs .. 404.6 μs)
std dev              5.965 μs   (3.134 μs .. 12.47 μs)

benchmarking normalization of benchmark/tests/TestTraceMono.hs
time                 403.6 μs   (401.8 μs .. 405.8 μs)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 404.4 μs   (402.6 μs .. 407.0 μs)
std dev              7.410 μs   (5.308 μs .. 10.66 μs)
variance introduced by outliers: 11% (moderately inflated)
```

So removing the check `$cshow` seems to make the normalization slightly faster.
Maybe the GHC Core to Clash Core conversion might be slightly faster because previously it didn't have to convert the show functions, but I wasn't able to measure that.
Do you know of any show functions that are particularly big?

**Comment by martijnbastiaan** [comment]
Is there anything we can do, even if it made it slower? And shouldn't unused expressions be cleaned up in the first place?

**Review by martijnbastiaan — APPROVED** [review]
LGTM. I think we should prioritize fixing this before worrying about the performance penalty. (But we probably should make an issue.)

**Comment by christiaanb** [comment]
Agree

**Pull request merged**
