### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by alex-mckenna**
## Still TODO:

  - [ ] Write a changelog entry (see changelog/README.md)
  - [ ] Check copyright notices are up to date in edited files

[comment]: # (Depending on the change, some of these points may not be necessary. If so, leave the boxes unchecked so it is easier for a reviewer to see what has been omitted.)

### CODE REVIEW

**Review by martijnbastiaan — APPROVED** [review]
It seems like this PR "activates" both evaluators. Could you add a comment (either in the PR description or commit messages, for archaeology purposes) on why this is?

**Comment by alex-mckenna** [comment]
I just noticed that the PR to remove the experimental evaluator flag has this at the start anyway:

> The partial evaluator should not replace the old evaluator
everywhere it is currently used, rather it should _only_ be used
for partial evaluation. This is because the partial evaluator may
not result in something that still repsects invariants (e.g. it
may not preserve invariants expected to hold after ANF).

Which I think covers what you wanted anyway @martijnbastiaan?

**Comment by martijnbastiaan** [comment]
Okay, so my confusion was that I thought PE would be enabled now on `master`. But as it stands, nothing calls it, so it's effectively disabled. Only the PE branch uses it.

**Comment by alex-mckenna** [comment]
> I thought PE would be enabled now on `master`

If I sneak that in on a PR titled "Small fixes" then please somebody just fire me :eyes:

**Comment by martijnbastiaan** [comment]
@christiaanb ^

**Pull request merged**
