### PR TITLE
Fix count{Trailing,Leading}Zeros constant folding

### PR DESCRIPTION
**Pull request by martijnbastiaan**
See the discussion at https://github.com/clash-lang/clash-compiler/pull/501

### CODE REVIEW

**Comment by christiaanb** [comment]
https://github.com/clash-lang/clash-compiler/pull/551 solves the same issue without needing a primitive

**Comment by martijnbastiaan** [comment]
> #551 solves the same issue without needing a primitive

I've ran a quick test and it doesn't seem so unfortunately.

**Comment by christiaanb** [comment]
Adding a primitive fixes the symptom, not the cause. If stuff still doesn't work after #551, then we need to investigate why.

**Comment by rowanG077** [comment]
I think the issue is that `foldl` is not implemented in the evaluator and blackboxes.

**Comment by martijnbastiaan** [comment]
Fixed in master.

**Comment by martijnbastiaan** [comment]
Ah nvm, you're right @rowanG077, CTZ still doesn't constant fold.

**Pull request closed without merging**
