### PR TITLE
Add a stack.yaml to install easily

### PR DESCRIPTION
**Pull request by junjihashimoto**
Hi,

Add a stack.yaml for compiling this project with stack.
(Cabal  sometimes happens build-dependency-problems.)

### CODE REVIEW

**Comment by christiaanb** [comment]
A couple of questions, since I'm not really familiar with `stack` (yet): 

* Why is the `resolver` set to `lts` instead of the `nightly`? 
* Why doesn't the `extra-deps` section include `ghc-typelits-natnormalise` and `ghc-tcplugins-extra`?

**Comment by junjihashimoto** [comment]
```nightly``` is just snapshot.
```lts``` is stable one. In genenal, ```lts``` is better.
https://github.com/fpco/lts-haskell#readme shows the details.

When a package of the ```lts``` does not match the version of cabal-file-dependency(for example a a package of ```lts```  is old) or  the ```lts``` does not have the package,
```extra-deps``` is needed

In our case, ```clash-prelude``` is old and ```ghc-tcpplugins-extra``` is not included.

**Comment by christiaanb** [comment]
Thanks for the patch and the explanation.

**Comment by junjihashimoto** [comment]
Thx, too.

**Pull request merged**
