### PR TITLE
`Exp.(^)` result is at least 1 bit

### LINKED ISSUE #1201: (8 :: Unsigned 8) ^ d0 ~ 0`
Reported by @leonschoorl at https://github.com/clash-lang/clash-compiler/issues/1183#issuecomment-597161331:

```
> Prelude> 2^0
1
```

vs

```
Clash.Prelude> (8::Unsigned 8) ^ d0
0
```

We should probably change

```haskell
type ExpResult (Index m) n = Index (m ^ n)
```

to

```haskell
type ExpResult (Index m) n = Max 1 (Index (m ^ n))
```

although I fear type-checking issues.

### PR DESCRIPTION
**Pull request by christiaanb**
Fixes #1201

### CODE REVIEW

**Comment by martijnbastiaan** [comment]
LGTM, but I'm not sure on backporting: we know the typecheckers don't handle solving `Max` that well (see 'Safe Index' PR). This could very well break designs.

**Comment by christiaanb** [comment]
Fair enough, I'll remove the backport.

**Comment by Jhana1** [comment]
I don't believe this is fixed.
`(ExpResult (Signed n) 0) ~ Signed 1` which = -1 which is certainly not correct right?

**Comment by christiaanb** [comment]
@Jhana1 you’re right. I’ll open a new ticket.

**Comment by christiaanb** [comment]
@Jhana1 seems this was already fixed by: https://github.com/clash-lang/clash-compiler/commit/574e3af82a7e0c36a87e7e2330735b54c407ba0d which is included in the 1.4 release

**Comment by Jhana1** [comment]
ahh sorry I missed that. Cheers.

**Pull request merged**
