### PR TITLE
Make clockResetError not error unnecessarily

### PR DESCRIPTION
**Pull request by cchalmers**

### CODE REVIEW

**Comment by cchalmers** [comment]
For the record, I’d prefer if this check was just removed. It often creates annoying false warnings.

**Comment by christiaanb** [comment]
@cchalmers I agree, the check should just be disabled for now, until we have a better implementation.

**Comment by martijnbastiaan** [comment]
For prosperity: 

```
in principle you shouldn't define a function with two identical clocks
but a polymorphic function with two different clocks, but instantiated to the same, is okay
so the way `clockResetErrors` should be implemented is as a traversal of the entire hierarchy of functions
before normalisation starts
not as a post-normalisation check of a function
but that's just for clocks
the reset one is different
because only two asynchronous reset lines are bad
so two synchronous lines is jsut fine (edited) 
but that information is only known after normalisation, because types need to be propagated (edited) 
```

**Comment by martijnbastiaan** [comment]
I've removed the check altogether. We should revisit this in the future.

**Pull request merged**
