### PR TITLE
Lock access to stdout in concurrent code

### PR DESCRIPTION
**Pull request by alex-mckenna**
## Still TODO:

  - [ ] Write a changelog entry (see changelog/README.md)
  - [x] Check copyright notices are up to date in edited files

[comment]: # (Depending on the change, some of these points may not be necessary. If so, leave the boxes unchecked so it is easier for a reviewer to see what has been omitted.)

### CODE REVIEW

**Comment by martijnbastiaan** [comment]
Hmm, would it be too much to switch to https://hackage.haskell.org/package/co-log?

**Comment by alex-mckenna** [comment]
For now yes, or rather I want to focus on #2035 for the time being. You can make a ticket and assign me to it if you want

**Comment by martijnbastiaan** [comment]
What happens with `DebugApplied` output? Does it have similar problems?

**Comment by alex-mckenna** [comment]
Not for now on `master`. I need to add this lock to `concurrent-normalization` so it doesn't become an issue though.
I almost made it before you had time to edit :eyes:

**Comment by alex-mckenna** [comment]
Is this approved btw @martijnbastiaan? If so you can merge it

**Pull request merged**
