### PR TITLE
Check whether MonoLocalBinds is enabled in modules (#595).

### PR DESCRIPTION
**Pull request by mmzx**

### CODE REVIEW

**Comment by martijnbastiaan** [comment]
GHC environment files strike again :S. The last issue is caused by clash-dev detecting an instance in the package-db (in `clash-lib-0.9999:GHC.BasicTypes.Extra`) and locally (`GHC.BasicTypes.Extra`):

```
      Matching instances:
        two instances involving out-of-scope types
          instance NFData BasicTypes.InlineSpec
            -- Defined in ‘clash-lib-0.9999:GHC.BasicTypes.Extra’
          instance NFData BasicTypes.InlineSpec
            -- Defined in ‘GHC.BasicTypes.Extra’
```

I think this should solve it:

```diff
diff --git a/clash-dev b/clash-dev
index d161d050..5443aa76 100755
--- a/clash-dev
+++ b/clash-dev
@@ -1,2 +1,13 @@
 #!/bin/sh
-ghci -fobject-code -iclash-lib/src -iclash-ghc/src-ghc -Wall -DTOOL_VERSION_ghc=\"$(ghc --numeric-version)\" Clash.hs
+GHC_VERSION=$(ghc --numeric-version)
+GHC_MAJOR_VERSION=$(echo ${GHC_VERSION} | tr -d '.' | head -c2)
+GHC_BIN_SRC=$(ls -d clash-ghc/src-bin-${GHC_MAJOR_VERSION}*)
+
+ghci \
+  -fobject-code \
+  -iclash-ghc/src-bin-common/ \
+  -i${GHC_BIN_SRC} \
+  -iclash-lib/src \
+  -iclash-ghc/src-ghc \
+  -Wall -DTOOL_VERSION_ghc=\"${GHC_VERSION}\" \
+  Clash.hs
diff --git a/clash-ghc/src-bin-common/Clash/GHCi/Common.hs b/clash-ghc/src-bin-common/Clash/GHCi/Common.hs
index 2c4ad077..ac5678af 100644
--- a/clash-ghc/src-bin-common/Clash/GHCi/Common.hs
+++ b/clash-ghc/src-bin-common/Clash/GHCi/Common.hs
@@ -1,3 +1,4 @@
+{-# LANGUAGE CPP        #-}
 {-# LANGUAGE LambdaCase #-}
 
 module Clash.GHCi.Common
```

**Comment by martijnbastiaan** [comment]
I've created a new PR for the patch I just posted: https://github.com/clash-lang/clash-compiler/pull/723.

**Comment by mmzx** [comment]
Sorry for the noise! I think should not use github from my phone...

**Comment by martijnbastiaan** [comment]
No problem! I'll see if I can write some tests later today, and then I'll merge it. Thanks :).

**Comment by mmzx** [comment]
Thanks @martijnbastiaan , please let me know if there is more to do on this issue. :)

**Comment by mmzx** [comment]
Regarding ghc-8.8.1 build failing, at least now I see a return code from `PortNamesWithRTree`, the previous builds were only time-outs.

**Comment by martijnbastiaan** [comment]
Hmm, `-9` usually means it got killed by the OOM killer..

**Comment by martijnbastiaan** [comment]
Just ignore CircleCI. I've pushed it to our local CI too.

**Comment by martijnbastiaan** [comment]
I've just ran a few tests, and it seems that the detection doesn't work for external packages. `modGraph2` only contains locally compiled modules. The way I tested it was:

1. Add `{-# LANGUAGE NoMonoLocalBinds #-}` to `Clash/Sized/Vector.hs`
2. Compile:

```haskell
module Test where

import Clash.Prelude

topEntity :: Vec 3 Int
topEntity = repeat 3
```

I think the check should also go into `LoadInterfaceFiles.loadExternalExprs` (or one of it's dependencies).

**Comment by mmzx** [comment]
Right @martijnbastiaan , I didn't think about testing it with the interface files. Thanks!
Reproduced your sample, so now I am using it to solve this.

**Comment by mmzx** [comment]
> I think the check should also go into `LoadInterfaceFiles.loadExternalExprs` (or one of it's dependencies).

@martijnbastiaan , I am reaching out to get ideas or suggestions, because there is a deadline on this and I seem to be stuck at it.

So far what I have concluded and found out (hopefully correctly):
- interface files (.hi) do not store the utilized language extension(s). So during de-serialization this is unavailable.
- `DynFlags` do store the Extensions utilized no other data type.
- however `DynFlags` does not carry `NoMonoLocalBinds` unless it is enabled in a local module or explicitly changed in the given ghc session.

Since a .hi file does not contain the extension list it would not trigger `DynFlags` to store `NoMonoLocalBinds`.

So I tried to go via:
data `ModIface` {mi_module} -> `moduleName` -> `getModSummary` -> `ms_hspp_opts` -> `DynFlags`.
But calling getModSummary tends to end up in exceptions, because of "Module not part of module graph exception."

Other this above chain I do not seem to find out how else to get to the utilized extensions of interface files.

**Comment by martijnbastiaan** [comment]
@mmzx, nice detective work. Well I guess that's it. If `hi` files don't store what language extensions it was built with (which makes sense I guess), the only thing we can do is actually change GHC instead of Clash. I'll create a new issue pointing out that we should extend GHC to support this feature. 

Thank you very much for your work. This get's us reeeealy close to 1.0, which is certainly exciting!

**Comment by mmzx** [comment]
Thank you @martijnbastiaan !

**Pull request merged**
