### PR TITLE
Render `vioProbe` in own module

### LINKED ISSUE #2500: VIO probes should be rendered in their own module to reduce naming collision probabilities
Instantiations such as the following `topEntity` currently generate naming collisions (also see #2497):

```haskell
topEntity ::
  "clk" ::: Clock Dom ->
  "in" ::: Signal Dom (Bit, Bit) ->
  "out" ::: Signal Dom (Bit, Bit)
topEntity ab = bundle (c, d)
 where
  c = vioProbe @Dom ("a" :> "b" :> Nil) ("c" :> Nil) 0 ab
  d = vioProbe @Dom ("a" :> "b" :> Nil) ("d" :> Nil) 0 ab
```

..due to the blackbox trying to define multiple `a` signals. If these probes were rendered in their own entities, this wouldn't have been a problem.

### PR DESCRIPTION
**Pull request by martijnbastiaan**
Fixes #2500

## Still TODO:

  - [X] ~~Write a changelog entry (see changelog/README.md)~~
  - [X] Check copyright notices are up to date in edited files
  - [x] Merge https://github.com/clash-lang/clash-compiler/pull/2511

### CODE REVIEW

**Comment by DigitalBrains1** [comment]
Maybe add
```haskell
-- See [Note: eta port names for trueDualPortBlockRam]
{-# OPTIONS_GHC -fno-do-lambda-eta-expansion #-}
```
?

**Comment by martijnbastiaan** [comment]
@christiaanb was pretty much against that last time around, but I don't remember the reasoning.

For this specific primitive: only `clk` will result in an HDL port name. The rest are blackbox-only arguments.

**Comment by DigitalBrains1** [comment]
> @christiaanb was pretty much against that last time around, but I don't remember the reasoning.

It was because in that case there was no need for the separate module. So you created a separate module specifically to get nice names. Here we *do* want a separate module for another reason. So we generate nice names for our separate module instead of a separate module for nice names. They're basically each other's reverse.

**Comment by martijnbastiaan** [comment]
Ok! Done!

**Review by kleinreact — APPROVED** [review]
LGTM

**Comment by martijnbastiaan** [comment]
Thanks! Will set it to draft to make sure it doesn't get merged before https://github.com/clash-lang/clash-compiler/pull/2511.

**Pull request merged**
