### PR TITLE
Clarify `BitPack` is not for creating custom encodings

### PR DESCRIPTION
**Pull request by DigitalBrains1**
It's easy to misconstrue the purpose of `BitPack`

## Still TODO:

  - ~~Write a changelog entry (see changelog/README.md)~~
  - [x] Check copyright notices are up to date in edited files

[comment]: # (Depending on the change, some of these points may not be necessary. If so, leave the boxes unchecked so it is easier for a reviewer to see what has been omitted.)

### CODE REVIEW

**Review by kleinreact — CHANGES_REQUESTED** [review]
Great to have it mentioned now. I only have some minor points:
* "_**not** the way_" is a little bit weak formulation, because it still suggests that it's fine to define custom instances overall. I would be more strict and use something link "_You should never define a custom instance yourself, but instead use ... . The purpose of `BitPack` is to provide uniform conversion methods only._". I also liked your explanation that "_It allows no creativity._" of #2574.
* I also would mention that `deriving (BitPack)` is fine too. At the moment it may be missinterpreted that defining a custom representation is the only way.
* > Rather than dictate what the bit representation in HDL is, a BitPack instance needs to exactly match that bit representation.

  I also got confused by that sentence, probably because its not immediately clear what "_that bit representation_" refers to.

**Comment by DigitalBrains1** [comment]
> * > Rather than dictate what the bit representation in HDL is, a BitPack instance needs to exactly match that bit representation.
>
>  I also got confused by that sentence, probably because its not immediately clear what "_that bit representation_" refers to.

I hoped it was clear that "that representation" in the second sentence fragment refers to "the representation" in the first sentence fragment, but would you rather see it repeated verbatim?

Rather than dictate what the bit representation in HDL is, a BitPack instance needs to exactly match the bit representation in HDL.

**Comment by kleinreact** [comment]
> Rather than dictate what the bit representation in HDL is, a BitPack instance needs to exactly match the bit representation in HDL.

It still confuses me. Maybe, because "_the bit representation_" is just very generic: so maybe elaborating on what bit representation is meant? I mean: I get what you wanna say with the sentence, but I have to read it at least twice and need to parse it carfully to get the meaning.

**Comment by DigitalBrains1** [comment]
I'll rephrase entirely.

**Review by kleinreact — APPROVED** [review]
LGTM now.

**Comment by DigitalBrains1** [comment]
@mergify rebase

**Pull request merged**
