### PR TITLE
Add `Counter a => Counter (Vec n a)` instance #2787

### PR DESCRIPTION
**Pull request by gergoerdi**
Fixes: #2787

### CODE REVIEW

**Comment by leonschoorl** [comment]
I think it would be good if the instance came with a comment about then endianness.
Something like https://github.com/clash-lang/clash-compiler/blob/96f741d01d9ad22ecb5635c862e3a8b640027c89/clash-prelude/src/Clash/Class/Counter/Internal.hs#L156-L168

I like having examples like that, because I can never which way round is supposed to be big or little.

**Comment by leonschoorl** [comment]
Also this endianness you implemented now is the "right" one I think.
Because its consistent with the view encoded in `BitPack`/[`Clash.Class.BitPack.BitIndex`](https://hackage.haskell.org/package/clash-prelude-1.8.1/docs/Clash-Class-BitPack-BitIndex.html):

```
clashi> countSucc @(Vec 3 Bit) (0 :> 0 :> 0 :> Nil)
0 :> 0 :> 1 :> Nil
clashi> msb @(Vec 3 Bit) (0 :> 0 :> 1 :> Nil)
0
clashi> lsb @(Vec 3 Bit) (0 :> 0 :> 1 :> Nil)
1
```

**Comment by martijnbastiaan** [comment]
@kloonbot run_ci ca3cba089d317a1cd517421c177345ab786fdacc

**Review by martijnbastiaan — APPROVED** [review]
Agreed with @leonschoorl on the examples / doctests. Other than that, LGTM.

**Comment by gergoerdi** [comment]
Where are we on this?

**Comment by martijnbastiaan** [comment]
@kloonbot run_ci ec242f66a60af2955c44901d4fb15c2a5ac6edab

**Comment by martijnbastiaan** [comment]
I'm okay with this if CI is.

**Pull request merged**
