### PR TITLE
Tutorial fixes

### PR DESCRIPTION
**Pull request by DigitalBrains1**
Fixes all over. Using CλaSH 1.0.1, code was tested to compile, example
commands where run and specified testbenches where run in both clashi
and in modelsim. No tests were done on an FPGA.

As discussed, this time against master instead of the 1.0 branch.

Some remarks about specific changes:
- JSON-key "type" was included for `blockRam#`, but not for `*#`. Added it for `*#`.

- `blockRam#` missed `KnownDomain`. Changed to match the source. Black boxes where copy-pasted from the real thing, which means `~ACTIVEEDGE` was introduced.

- I had to do three takes to read the sentence

    > Signals of product types and product types (to which tuples belong) of signals are __isomorphic__ [...]

    because of the parenthetical. The sentence is already complicated, better to move that information to a new sentence, IMHO:

    > Signals of product types and product types of signals are __isomorphic__ due to synchronisity principle, but are not (structurally) equal. Tuples are a product type. Use the `bundle` function to convert from a product

    For the record, my brain was parsing that tuples belong to the group defined as "signals of product types and product types", i.e. product types and signals thereof, and after that the sentence broke down semantically.

### CODE REVIEW

**Comment by martijnbastiaan** [comment]
@DigitalBrains1 Your tests should work if you rebase on master. Sorry about that.

**Comment by martijnbastiaan** [comment]
Don't worry about making another PR, just force push! :)

**Comment by DigitalBrains1** [comment]
@martijnbastiaan I'm not sure what I should do. This single commit PR is on top of 2abb2c50, what else should it be?

**Comment by DigitalBrains1** [comment]
Oh, it seems my fetch failed... it's not on top. I'll fix it.

**Comment by martijnbastiaan** [comment]
I see Christiaan added you to the organization too (sorry about any duplicate e-mails you might now get..). If you create a branch on `clash-lang/clash-compiler` you should trigger our own CI which should run quite a bit faster.

**Comment by martijnbastiaan** [comment]
Seems like Circle CI ran out of memory again.. Issue report: https://github.com/clash-lang/clash-compiler/issues/806. 

Thanks for the fixes!

**Pull request merged**
